# Site settings
title: matplotlib colormaps
tag_text: mpl colormaps
description: An overview of the colormaps recommended to replace 'jet' as default.

# Build settings
markdown: redcarpet

exclude: ["README.md"]
