# Site settings
title: matplotlib colormaps
tag_text: mpl colormaps
description: An overview of the colormaps recommended to replace 'jet' as default.

# Build settings
markdown: kramdown

kramdown:
    input: GFM
    use_coderay: true
    coderay:
        coderay_line_numbers: nil

exclude: ["README.md"]
